### PR TITLE
Use new hierarchies of contract groups.

### PR DESCRIPTION
**Pull request by jrossignol**
I used this as my test bed for the contract group hierarchy functionality.  You may want to hold off merging until 0.7.12 is released (likely today or tomorrow).

### CODE REVIEW

**Comment by severedsolo** [comment]
Did it not work? why was it reverted?

**Comment by jrossignol** [comment]
I'm going to guess he missed my "dependent on 0.7.12" comment.  Anyway, 0.7.12 is out now. :wink:

**Comment by severedsolo** [comment]
Doesn't matter, I'm not releasing a new update until after 1.0 anyway. Anyhoo updated my master file again, changes committed. Cheers for implementing that, will make life a bit easier

**Comment by metl** [comment]
I meant to pull it into my fork and pulled it into the main.

**Pull request merged**
