### PR TITLE
Failsafe System

### PR DESCRIPTION
**Pull request by metl**
I believe with Nightingale's help we were able to finally knock out the last remaining issues with the failsafe. These changes should force the contracts to check to see if the station is in orbit, or in the case of the core, ensure it is not already there. I didn't test them individually, but it worked with the power module and core files properly.

I also think I was able to restore the mod support that i accidentally removed with the last series of changes.

### CODE REVIEW

**Comment by severedsolo** [comment]
I'll do a pull tonight

**Comment by metl** [comment]
The next update to Contract Configurator fixes the bug (it was on Nightingale's end.) Files are safe to merge, but CC requirement needs to be moved up to 0.7.8

**Comment by severedsolo** [comment]
Merge done. Seen a couple of bits that need to be cleaned up, but I'll sort that out

**Comment by severedsolo** [comment]
Yeah that works pretty well, good work! For some reason crew rotation wouldn't except the expression (but I have no idea why) - and I found a problem with the EVA mission (not you, but CC I think). 1.0 is looking pretty good though!

**Comment by metl** [comment]
Anything specific you want me to try to tackle next?

**Comment by severedsolo** [comment]
I'm thinking next we should push forward for multiple bodies (mun and minmus first I think), 

As the code is likely to change as I iron out the 1.0 bugs before release it may be an idea to wait until I release.

I may not be on very much for the next few days, I am off work til Tuesday and plan to take a bit of a break.

**Pull request merged**
